# Pipeline script to deploy ArchiMate model as HTML to GitHub Pages

image: maven:3.6.3

pipelines:
  branches:
    master:
      - step:
          name: Deploy to GitHub Pages
          clone:
            enabled: true
          script:
            - git remote add gh git@github.com:btk467/wcb-architecture-reporting.git
            - git push gh master


