# Pipeline script to deploy ArchiMate model as HTML to GitHub Pages

image: maven:3.6.3

pipelines:
  branches:
    master:
      - step:
          name: Deploy to GitHub Pages
          clone:
            enabled: true
          script:
            - git remote add gh https://github.com/btk467/wcb-architecture-reporting.git
            - git pull gh
            - git push gh
            #- apt-get update && apt-get install -y git
            #- git clone https://${BITBUCKET_GIT_HTTP_ORIGIN} /tmp/repo
            #- rm -rf /tmp/repo/*
            #- cp -Rf ${BITBUCKET_CLONE_DIR}/export/* /tmp/repo/
            #- cd /tmp/repo
            #- git config user.email "your-email@example.com"
            #- git config user.name "Your Name"
            #- git add .
            #- git commit -m "Deploy ArchiMate model as HTML to GitHub Pages"
            #- git push --force "https://${GITHUB_USERNAME}:${GITHUB_ACCESS_TOKEN}@github.com/${GITHUB_REPO}" master

